services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=competec
      - POSTGRES_USER=competec_user
      - POSTGRES_PASSWORD=zBb}5sLOQLk`<8xlo8)c+/H3v/£1Fd<Ci
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: