services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media
    expose:
      - 8000
    env_file:
      - path: ./backend/.env
        required: false
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-competec}
      - POSTGRES_USER=${POSTGRES_USER:-competec_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-competec_password}
    restart: always

 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
 
    environment:
      - NEXT_PUBLIC_API_URL=https://api.v4jasson.com.br
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres_data:
