# Generated by Django 5.1.4 on 2025-12-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Formato recomendado: JPG ou PNG. Dimensões ideais: 1200x630 pixels.', null=True, upload_to='blog_covers/', verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Escreva o corpo do seu artigo aqui.', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Marque esta caixa apenas quando quiser que o artigo apareça no site.', verbose_name='Publicado?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text="Este campo é preenchido automaticamente com base no título. Ex: 'meu-titulo-legal'.", unique=True, verbose_name='URL Amigável'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Digite o título principal do artigo.', max_length=200, verbose_name='Título'),
        ),
    ]
