# Generated by Django 5.1.4 on 2025-12-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Imagem Esquerda')),
                ('card_title', models.CharField(max_length=100, verbose_name='Título do Card (H3)')),
                ('card_description', models.TextField(verbose_name='Descrição do Card')),
                ('section_subtitle', models.CharField(help_text='Texto menor acima do título', max_length=100, verbose_name='Subtítulo (H2)')),
                ('section_title', models.CharField(max_length=200, verbose_name='Título Principal')),
                ('section_description', models.TextField(verbose_name='Texto Descritivo (H3)')),
            ],
            options={
                'verbose_name': 'Seção Quem Somos',
                'verbose_name_plural': 'Seção Quem Somos',
            },
        ),
        migrations.CreateModel(
            name='Differentiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Se marcado, fica laranja. Se não, branco.', verbose_name='É Destaque?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Diferencial',
                'verbose_name_plural': 'Diferenciais (Folders)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Usinagem de Precisão', max_length=200, verbose_name='Título (H1)')),
                ('subtitle', models.CharField(help_text='Ex: Soluções para Indústria 4.0', max_length=200, verbose_name='Subtítulo (H4)')),
                ('cta_text', models.CharField(default='Fale Conosco', max_length=50, verbose_name='Texto do Botão')),
                ('cta_link', models.CharField(default='#contato', max_length=200, verbose_name='Link do Botão')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Imagem Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Seção Hero',
                'verbose_name_plural': 'Seção Hero',
            },
        ),
        migrations.CreateModel(
            name='HistorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtítulo')),
                ('description', models.TextField(verbose_name='Texto Principal')),
                ('image', models.ImageField(upload_to='history/', verbose_name='Imagem Direita')),
                ('background_text', models.CharField(help_text='O texto grande transparente no fundo', max_length=100, verbose_name='Texto de Fundo (Efeito)')),
            ],
            options={
                'verbose_name': 'Seção História',
                'verbose_name_plural': 'Seção História',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Logo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros / Cases',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon', models.ImageField(upload_to='services/icons/', verbose_name='Ícone')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['order'],
            },
        ),
    ]
