# Generated by Django 5.1.4 on 2025-12-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='card_description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='card_title',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='section_description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='section_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='section_title',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='text',
            field=models.TextField(default='', verbose_name='Texto Principal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(upload_to='about/', verbose_name='Imagem'),
        ),
    ]
