# Generated by Django 5.1.4 on 2025-12-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_is_active_alter_service_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Nossos Serviços', max_length=100, verbose_name='Chapéu (Texto Laranja)')),
                ('title', models.CharField(default='Quais são os nossos serviços?', max_length=200, verbose_name='Título Principal')),
                ('image', models.ImageField(upload_to='services_hero/', verbose_name='Imagem Lateral Grande')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Seção Serviços (Capa)',
                'verbose_name_plural': 'Seção Serviços (Capa)',
            },
        ),
    ]
