# Generated by Django 5.1.4 on 2025-12-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicessection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Serviço (Card)', 'verbose_name_plural': 'Serviços (Cards)'},
        ),
    ]
