# Generated by Django 5.1.4 on 2025-12-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historysection',
            options={'verbose_name': 'Seção História (Quem é...)', 'verbose_name_plural': 'Seção História (Quem é...)'},
        ),
        migrations.RenameField(
            model_name='historysection',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='historysection',
            name='background_text',
        ),
        migrations.RemoveField(
            model_name='historysection',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='historysection',
            name='footer_text',
            field=models.CharField(blank=True, help_text='A frase laranja centralizada abaixo', max_length=300, verbose_name='Texto Destaque (Rodapé)'),
        ),
        migrations.AddField(
            model_name='historysection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='historysection',
            name='tag',
            field=models.CharField(default='Quem Somos', max_length=50, verbose_name='Tag Superior (Laranja)'),
        ),
        migrations.AlterField(
            model_name='historysection',
            name='image',
            field=models.ImageField(upload_to='history/', verbose_name='Imagem Aérea'),
        ),
        migrations.AlterField(
            model_name='historysection',
            name='title',
            field=models.CharField(default='Quem é a Competec?', max_length=200, verbose_name='Título Principal'),
        ),
    ]
