# Generated by Django 5.1.4 on 2025-12-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_historysection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Pessoa')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Cargo/Empresa (Opcional)')),
                ('text', models.TextField(verbose_name='Depoimento')),
                ('image', models.ImageField(upload_to='testimonials/', verbose_name='Foto do Perfil')),
                ('rating', models.IntegerField(default=5, verbose_name='Estrelas (1-5)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos / Reviews',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Parceiro técnico de indústrias\nQue não podem parar', max_length=200, verbose_name='Título Principal')),
                ('subtitle', models.TextField(verbose_name='Texto de Apoio')),
                ('image', models.ImageField(upload_to='testimonials_bg/', verbose_name='Imagem de Fundo (Rapaz)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Seção Depoimentos (Capa)',
                'verbose_name_plural': 'Seção Depoimentos (Capa)',
            },
        ),
    ]
