# Generated by Django 5.1.4 on 2025-12-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testimonial_testimonialssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Post')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Capa do Post')),
                ('date', models.DateField(default='2025-10-10', verbose_name='Data de Publicação')),
                ('link', models.CharField(default='#', help_text='Link para a página interna', max_length=200, verbose_name='Link do Post')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Post do Blog',
                'verbose_name_plural': 'Posts do Blog',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Blog', max_length=50, verbose_name='Tag Superior (Laranja)')),
                ('title', models.CharField(default='Conteúdo técnico sobre gestão industrial', max_length=200, verbose_name='Título Principal')),
                ('subtitle', models.CharField(default='conformidade e eficiência operacional.', max_length=200, verbose_name='Texto de Apoio (Direita)')),
                ('cta_text', models.CharField(default='Ver todas as postagens', max_length=50, verbose_name='Texto do Botão')),
                ('cta_link', models.CharField(default='/blog', max_length=200, verbose_name='Link do Botão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Seção Blog (Capa)',
                'verbose_name_plural': 'Seção Blog (Capa)',
            },
        ),
    ]
