# Generated by Django 5.1.4 on 2025-12-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogpost_blogsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='link',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Time Competec', max_length=100, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='', verbose_name='Conteúdo Completo do Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='', help_text='Identificador único para a URL (ex: titulo-do-post)', unique=True, verbose_name='Slug (URL)'),
            preserve_default=False,
        ),
    ]
