# Generated by Django 5.1.4 on 2025-12-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_blogpost_link_blogpost_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='footer/', verbose_name='Logo do Rodapé')),
                ('description', models.TextField(default='Trabalhamos há mais de 20 anos para facilitar a vida de gestores...', verbose_name='Texto Sobre (Coluna 1)')),
                ('address_title', models.CharField(default='Endereço', max_length=50, verbose_name='Título Endereço')),
                ('address_text', models.TextField(verbose_name='Endereço Completo')),
                ('contact_title', models.CharField(default='Contato', max_length=50, verbose_name='Título Contato')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefone Fixo')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('whatsapp_2', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp Secundário')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='Youtube')),
                ('copyright_text', models.CharField(default='Todos os direitos reservados @2025 - Feito com carinho pela V4 Jassoon Oliverira&Co.', max_length=200, verbose_name='Texto Direitos Autorais')),
            ],
            options={
                'verbose_name': 'Configuração do Rodapé',
                'verbose_name_plural': 'Configuração do Rodapé',
            },
        ),
    ]
