# Generated by Django 5.1.4 on 2025-12-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_footerconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerconfig',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='Linkedin'),
        ),
    ]
