# Generated by Django 5.1.4 on 2025-12-26 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_footerconfig_linkedin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'Página Quem Somos', 'verbose_name_plural': 'Página Quem Somos'},
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_banner/', verbose_name='Banner do Topo (Interna)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='cta_link',
            field=models.CharField(default='https://wa.me/...', max_length=200, verbose_name='Link do WhatsApp'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='cta_text',
            field=models.CharField(default='Entre em Contato', max_length=50, verbose_name='Texto do Botão'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='map_embed_url',
            field=models.TextField(blank=True, verbose_name='Link Embed do Mapa'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Subtítulo (Interna)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='tag',
            field=models.CharField(default='Quem Somos', max_length=50, verbose_name='Tag Superior'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID do Vídeo Youtube'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(upload_to='about/', verbose_name='Imagem Principal (Direita)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default='Nossa História', max_length=200, verbose_name='Título Principal'),
        ),
        migrations.CreateModel(
            name='AboutGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_gallery/', verbose_name='Imagem da Galeria')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.aboutsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutValueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='about_icons/', verbose_name='Ícone')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Texto Curto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.aboutsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
