# Generated by Django 5.1.4 on 2025-12-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_aboutsection_options_aboutsection_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='internal_image',
            field=models.ImageField(blank=True, help_text='Se não enviar, usa a imagem da Home', null=True, upload_to='about_internal/', verbose_name='Imagem Lateral (Interna)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(upload_to='about/', verbose_name='Imagem Principal (Home)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='map_embed_url',
            field=models.TextField(blank=True, help_text='Cole o código de incorporação (iframe) ou o link', verbose_name='Link ou Iframe do Mapa'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Subtítulo (Destaque Interna)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='Cole o link completo ou apenas o ID', max_length=200, verbose_name='Link ou ID do Youtube'),
        ),
    ]
