# Generated by Django 5.1.4 on 2025-12-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aboutsection_internal_image_alter_aboutsection_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='internal_text',
            field=models.TextField(blank=True, help_text='O texto longo explicativo que vai abaixo do destaque', verbose_name='Texto Completo (Interna)'),
        ),
    ]
