# Generated by Django 5.1.4 on 2026-01-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aboutsection_internal_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
