# Generated by Django 5.1.4 on 2026-01-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_service_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Serviço (Card + Interna)', 'verbose_name_plural': '2. Soluções e Serviços'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='cta_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link do Botão'),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_text',
            field=models.CharField(default='Falar com Especialista', max_length=50, verbose_name='Texto do Botão'),
        ),
        migrations.AddField(
            model_name='service',
            name='internal_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/internal/', verbose_name='Imagem Interna'),
        ),
        migrations.AddField(
            model_name='service',
            name='internal_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo Interno'),
        ),
        migrations.AddField(
            model_name='service',
            name='internal_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Completo'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(default='', verbose_name='Descrição Curta (Card)'),
            preserve_default=False,
        ),
    ]
