# Generated by Django 5.1.4 on 2026-01-08 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_service_options_remove_service_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Página')),
                ('slug', models.SlugField(help_text='Ex: cidades-atendidas', unique=True, verbose_name='Slug (URL)')),
                ('banner', models.ImageField(upload_to='info_banners/', verbose_name='Banner do Topo')),
                ('intro_text', models.TextField(blank=True, help_text='Texto principal', verbose_name='Texto Introdutório (HTML)')),
                ('regions_content', models.TextField(blank=True, help_text='Cole a tabela aqui', verbose_name='Lista de Regiões/Cidades (HTML)')),
                ('cta_title', models.CharField(default='Entre em contato', max_length=100, verbose_name='Título CTA')),
                ('cta_link', models.CharField(default='#contato', max_length=200, verbose_name='Link do Botão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Página de Informação',
                'verbose_name_plural': 'Páginas de Informações',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='regions_served',
            field=models.TextField(blank=True, verbose_name='Cidades/Regiões Atendidas'),
        ),
        migrations.AddField(
            model_name='service',
            name='rich_text',
            field=models.TextField(blank=True, verbose_name='Texto Completo (HTML)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='internal_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_internal/', verbose_name='Imagem Lateral (Interna)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='internal_text',
            field=models.TextField(blank=True, verbose_name='Texto Completo (Interna)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='map_embed_url',
            field=models.TextField(blank=True, verbose_name='Link ou Iframe do Mapa'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link ou ID do Youtube'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text='Identificador único para a URL', unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='differentiator',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='É Destaque?'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='copyright_text',
            field=models.CharField(default='Todos os direitos reservados...', max_length=200, verbose_name='Texto Direitos Autorais'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='description',
            field=models.TextField(default='Trabalhamos há mais de 20 anos...', verbose_name='Texto Sobre (Coluna 1)'),
        ),
        migrations.AlterField(
            model_name='historysection',
            name='footer_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Texto Destaque (Rodapé)'),
        ),
        migrations.CreateModel(
            name='InformationGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info_gallery/', verbose_name='Imagem')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.informationpage')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Galeria desta Página',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Imagem')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Legenda (Alt)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.service')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Galeria de Imagens do Serviço',
                'ordering': ['order'],
            },
        ),
    ]
