# Generated by Django 5.1.4 on 2026-01-08 20:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_informationpage_service_regions_served_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpage',
            name='intro_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Escreva o texto como no Word', verbose_name='Texto Introdutório'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='regions_content',
            field=models.TextField(blank=True, help_text='Digite as cidades separadas por vírgula. Ex: Curitiba, São Paulo, Anápolis, Goiânia', verbose_name='Lista de Cidades/Regiões'),
        ),
    ]
