# Generated by Django 5.1.4 on 2026-06-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_informationpage_intro_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='navbar/', verbose_name='Logo do Site')),
                ('alt_text', models.CharField(default='Competec', max_length=255, verbose_name='Texto Alternativo (Alt)')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': 'ConfiguraÃ§Ã£o do Navbar (Logo)',
                'verbose_name_plural': 'ConfiguraÃ§Ã£o do Navbar (Logo)',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'PÃ¡gina Quem Somos', 'verbose_name_plural': 'PÃ¡gina Quem Somos'},
        ),
        migrations.AlterModelOptions(
            name='blogsection',
            options={'verbose_name': 'SeÃ§Ã£o Blog (Capa)', 'verbose_name_plural': 'SeÃ§Ã£o Blog (Capa)'},
        ),
        migrations.AlterModelOptions(
            name='footerconfig',
            options={'verbose_name': 'ConfiguraÃ§Ã£o do RodapÃ©', 'verbose_name_plural': 'ConfiguraÃ§Ã£o do RodapÃ©'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'SeÃ§Ã£o Hero', 'verbose_name_plural': 'SeÃ§Ã£o Hero'},
        ),
        migrations.AlterModelOptions(
            name='historysection',
            options={'verbose_name': 'SeÃ§Ã£o HistÃ³ria (Quem Ã©...)', 'verbose_name_plural': 'SeÃ§Ã£o HistÃ³ria (Quem Ã©...)'},
        ),
        migrations.AlterModelOptions(
            name='informationgalleryimage',
            options={'ordering': ['order'], 'verbose_name': 'Imagem da Galeria', 'verbose_name_plural': 'Galeria desta PÃ¡gina'},
        ),
        migrations.AlterModelOptions(
            name='informationpage',
            options={'verbose_name': 'PÃ¡gina de InformaÃ§Ã£o', 'verbose_name_plural': 'PÃ¡ginas de InformaÃ§Ãµes'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'ServiÃ§o (Card + Interna)', 'verbose_name_plural': '2. SoluÃ§Ãµes e ServiÃ§os'},
        ),
        migrations.AlterModelOptions(
            name='servicegalleryimage',
            options={'ordering': ['order'], 'verbose_name': 'Imagem da Galeria', 'verbose_name_plural': 'Galeria de Imagens do ServiÃ§o'},
        ),
        migrations.AlterModelOptions(
            name='servicessection',
            options={'verbose_name': 'SeÃ§Ã£o ServiÃ§os (Capa)', 'verbose_name_plural': 'SeÃ§Ã£o ServiÃ§os (Capa)'},
        ),
        migrations.AlterModelOptions(
            name='testimonialssection',
            options={'verbose_name': 'SeÃ§Ã£o Depoimentos (Capa)', 'verbose_name_plural': 'SeÃ§Ã£o Depoimentos (Capa)'},
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='cta_text',
            field=models.CharField(default='Entre em Contato', max_length=50, verbose_name='Texto do BotÃ£o'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='SubtÃ\xadtulo (Destaque Interna)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default='Nossa HistÃ³ria', max_length=200, verbose_name='TÃ\xadtulo Principal'),
        ),
        migrations.AlterField(
            model_name='aboutvaluecard',
            name='icon',
            field=models.ImageField(upload_to='about_icons/', verbose_name='Ã\x8dcone'),
        ),
        migrations.AlterField(
            model_name='aboutvaluecard',
            name='title',
            field=models.CharField(max_length=100, verbose_name='TÃ\xadtulo'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='ConteÃºdo Completo do Post'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(default='2025-10-10', verbose_name='Data de PublicaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text='Identificador Ãºnico para a URL', unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='TÃ\xadtulo do Post'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='cta_link',
            field=models.CharField(default='/blog', max_length=200, verbose_name='Link do BotÃ£o'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='cta_text',
            field=models.CharField(default='Ver todas as postagens', max_length=50, verbose_name='Texto do BotÃ£o'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='subtitle',
            field=models.CharField(default='conformidade e eficiÃªncia operacional.', max_length=200, verbose_name='Texto de Apoio (Direita)'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='title',
            field=models.CharField(default='ConteÃºdo tÃ©cnico sobre gestÃ£o industrial', max_length=200, verbose_name='TÃ\xadtulo Principal'),
        ),
        migrations.AlterField(
            model_name='differentiator',
            name='description',
            field=models.TextField(verbose_name='DescriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='differentiator',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='Ã‰ Destaque?'),
        ),
        migrations.AlterField(
            model_name='differentiator',
            name='title',
            field=models.CharField(max_length=100, verbose_name='TÃ\xadtulo'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='address_text',
            field=models.TextField(verbose_name='EndereÃ§o Completo'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='address_title',
            field=models.CharField(default='EndereÃ§o', max_length=50, verbose_name='TÃ\xadtulo EndereÃ§o'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='contact_title',
            field=models.CharField(default='Contato', max_length=50, verbose_name='TÃ\xadtulo Contato'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='description',
            field=models.TextField(default='Trabalhamos hÃ¡ mais de 20 anos...', verbose_name='Texto Sobre (Coluna 1)'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='logo',
            field=models.ImageField(upload_to='footer/', verbose_name='Logo do RodapÃ©'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='whatsapp_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='WhatsApp SecundÃ¡rio'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_link',
            field=models.CharField(default='#contato', max_length=200, verbose_name='Link do BotÃ£o'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_text',
            field=models.CharField(default='Fale Conosco', max_length=50, verbose_name='Texto do BotÃ£o'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(help_text='Ex: SoluÃ§Ãµes para IndÃºstria 4.0', max_length=200, verbose_name='SubtÃ\xadtulo (H4)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(help_text='Ex: Usinagem de PrecisÃ£o', max_length=200, verbose_name='TÃ\xadtulo (H1)'),
        ),
        migrations.AlterField(
            model_name='historysection',
            name='footer_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Texto Destaque (RodapÃ©)'),
        ),
        migrations.AlterField(
            model_name='historysection',
            name='image',
            field=models.ImageField(upload_to='history/', verbose_name='Imagem AÃ©rea'),
        ),
        migrations.AlterField(
            model_name='historysection',
            name='title',
            field=models.CharField(default='Quem Ã© a Competec?', max_length=200, verbose_name='TÃ\xadtulo Principal'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='cta_link',
            field=models.CharField(default='#contato', max_length=200, verbose_name='Link do BotÃ£o'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='cta_title',
            field=models.CharField(default='Entre em contato', max_length=100, verbose_name='TÃ\xadtulo CTA'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='intro_text',
            field=models.TextField(blank=True, help_text='Escreva o texto como no Word', verbose_name='Texto Introdutorio'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='TÃ\xadtulo da PÃ¡gina'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cta_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link do BotÃ£o'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cta_text',
            field=models.CharField(default='Falar com Especialista', max_length=50, verbose_name='Texto do BotÃ£o'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Ã\x8dcone/Imagem'),
        ),
        migrations.AlterField(
            model_name='service',
            name='internal_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SubtÃ\xadtulo Interno'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordem de ExibiÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='service',
            name='regions_served',
            field=models.TextField(blank=True, verbose_name='Cidades/RegiÃµes Atendidas'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(verbose_name='DescriÃ§Ã£o Curta (Card)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='TÃ\xadtulo'),
        ),
        migrations.AlterField(
            model_name='servicessection',
            name='heading',
            field=models.CharField(default='Nossos ServiÃ§os', max_length=100, verbose_name='ChapÃ©u (Texto Laranja)'),
        ),
        migrations.AlterField(
            model_name='servicessection',
            name='title',
            field=models.CharField(default='Quais sÃ£o os nossos serviÃ§os?', max_length=200, verbose_name='TÃ\xadtulo Principal'),
        ),
        migrations.AlterField(
            model_name='testimonialssection',
            name='title',
            field=models.CharField(default='Parceiro tÃ©cnico de indÃºstrias\nQue nÃ£o podem parar', max_length=200, verbose_name='TÃ\xadtulo Principal'),
        ),
    ]
