# Generated by Django 5.1.4 on 2026-06-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_navbarconfig_alter_aboutsection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'Página Quem Somos', 'verbose_name_plural': 'Página Quem Somos'},
        ),
        migrations.AlterModelOptions(
            name='blogsection',
            options={'verbose_name': 'Seção Blog (Capa)', 'verbose_name_plural': 'Seção Blog (Capa)'},
        ),
        migrations.AlterModelOptions(
            name='footerconfig',
            options={'verbose_name': 'Configuração do Rodapé', 'verbose_name_plural': 'Configuração do Rodapé'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Seção Hero', 'verbose_name_plural': 'Seção Hero'},
        ),
        migrations.AlterModelOptions(
            name='historysection',
            options={'verbose_name': 'Seção História (Quem é...)', 'verbose_name_plural': 'Seção História (Quem é...)'},
        ),
        migrations.AlterModelOptions(
            name='informationgalleryimage',
            options={'ordering': ['order'], 'verbose_name': 'Imagem da Galeria', 'verbose_name_plural': 'Galeria desta Página'},
        ),
        migrations.AlterModelOptions(
            name='informationpage',
            options={'verbose_name': 'Página de Informação', 'verbose_name_plural': 'Páginas de Informações'},
        ),
        migrations.AlterModelOptions(
            name='navbarconfig',
            options={'verbose_name': 'Configuração do Navbar (Logo)', 'verbose_name_plural': 'Configuração do Navbar (Logo)'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Serviço (Card + Interna)', 'verbose_name_plural': '2. Soluções e Serviços'},
        ),
        migrations.AlterModelOptions(
            name='servicegalleryimage',
            options={'ordering': ['order'], 'verbose_name': 'Imagem da Galeria', 'verbose_name_plural': 'Galeria de Imagens do Serviço'},
        ),
        migrations.AlterModelOptions(
            name='servicessection',
            options={'verbose_name': 'Seção Serviços (Capa)', 'verbose_name_plural': 'Seção Serviços (Capa)'},
        ),
        migrations.AlterModelOptions(
            name='testimonialssection',
            options={'verbose_name': 'Seção Depoimentos (Capa)', 'verbose_name_plural': 'Seção Depoimentos (Capa)'},
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='cta_text',
            field=models.CharField(default='Entre em Contato', max_length=50, verbose_name='Texto do Botão'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Subtítulo (Destaque Interna)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default='Nossa História', max_length=200, verbose_name='Título Principal'),
        ),
        migrations.AlterField(
            model_name='aboutvaluecard',
            name='icon',
            field=models.ImageField(upload_to='about_icons/', verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='aboutvaluecard',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='Conteúdo Completo do Post'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(default='2025-10-10', verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text='Identificador único para a URL', unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título do Post'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='cta_link',
            field=models.CharField(default='/blog', max_length=200, verbose_name='Link do Botão'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='cta_text',
            field=models.CharField(default='Ver todas as postagens', max_length=50, verbose_name='Texto do Botão'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='subtitle',
            field=models.CharField(default='conformidade e eficiência operacional.', max_length=200, verbose_name='Texto de Apoio (Direita)'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='title',
            field=models.CharField(default='Conteúdo técnico sobre gestão industrial', max_length=200, verbose_name='Título Principal'),
        ),
        migrations.AlterField(
            model_name='differentiator',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='differentiator',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='É Destaque?'),
        ),
        migrations.AlterField(
            model_name='differentiator',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='address_text',
            field=models.TextField(verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='address_title',
            field=models.CharField(default='Endereço', max_length=50, verbose_name='Título Endereço'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='contact_title',
            field=models.CharField(default='Contato', max_length=50, verbose_name='Título Contato'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='description',
            field=models.TextField(default='Trabalhamos há mais de 20 anos...', verbose_name='Texto Sobre (Coluna 1)'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='logo',
            field=models.ImageField(upload_to='footer/', verbose_name='Logo do Rodapé'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='whatsapp_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='WhatsApp Secundário'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_link',
            field=models.CharField(default='#contato', max_length=200, verbose_name='Link do Botão'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_text',
            field=models.CharField(default='Fale Conosco', max_length=50, verbose_name='Texto do Botão'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(help_text='Ex: Soluções para Indústria 4.0', max_length=200, verbose_name='Subtítulo (H4)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(help_text='Ex: Usinagem de Precisão', max_length=200, verbose_name='Título (H1)'),
        ),
        migrations.AlterField(
            model_name='historysection',
            name='footer_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Texto Destaque (Rodapé)'),
        ),
        migrations.AlterField(
            model_name='historysection',
            name='image',
            field=models.ImageField(upload_to='history/', verbose_name='Imagem Aérea'),
        ),
        migrations.AlterField(
            model_name='historysection',
            name='title',
            field=models.CharField(default='Quem é a Competec?', max_length=200, verbose_name='Título Principal'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='cta_link',
            field=models.CharField(default='#contato', max_length=200, verbose_name='Link do Botão'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='cta_title',
            field=models.CharField(default='Entre em contato', max_length=100, verbose_name='Título CTA'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='regions_content',
            field=models.TextField(blank=True, help_text='Digite as cidades separadas por vírgula. Ex: Curitiba, São Paulo, Anápolis, Goiânia', verbose_name='Lista de Cidades/Regiões'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título da Página'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cta_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link do Botão'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cta_text',
            field=models.CharField(default='Falar com Especialista', max_length=50, verbose_name='Texto do Botão'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Ícone/Imagem'),
        ),
        migrations.AlterField(
            model_name='service',
            name='internal_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo Interno'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='service',
            name='regions_served',
            field=models.TextField(blank=True, verbose_name='Cidades/Regiões Atendidas'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(verbose_name='Descrição Curta (Card)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='servicessection',
            name='heading',
            field=models.CharField(default='Nossos Serviços', max_length=100, verbose_name='Chapéu (Texto Laranja)'),
        ),
        migrations.AlterField(
            model_name='servicessection',
            name='title',
            field=models.CharField(default='Quais são os nossos serviços?', max_length=200, verbose_name='Título Principal'),
        ),
        migrations.AlterField(
            model_name='testimonialssection',
            name='title',
            field=models.CharField(default='Parceiro técnico de indústrias\nQue não podem parar', max_length=200, verbose_name='Título Principal'),
        ),
    ]
