# Generated by Django 5.1.4 on 2026-06-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_aboutsection_options_alter_blogsection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.TextField(help_text='Ex: Soluções para Indústria 4.0', verbose_name='Subtítulo (H4)'),
        ),
    ]
