# Generated by Django 5.1.4 on 2026-08-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_service_landing_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarconfig',
            name='floating_whatsapp_link',
            field=models.CharField(blank=True, default='https://wa.me/5562995530750', max_length=200, verbose_name='Link do WhatsApp (Botão Flutuante)'),
        ),
    ]
