# Generated by Django 5.1.4 on 2026-08-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_navbarconfig_floating_whatsapp_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbarconfig',
            options={'verbose_name': 'Configurações Gerais (Logo, WhatsApp e Redes Sociais)', 'verbose_name_plural': 'Configurações Gerais (Logo, WhatsApp e Redes Sociais)'},
        ),
        migrations.AlterField(
            model_name='navbarconfig',
            name='floating_whatsapp_link',
            field=models.CharField(blank=True, default='https://wa.me/5562995530750', help_text='Link do botãozinho verde de WhatsApp que fica fixo no canto da tela em todas as páginas. Formato: https://wa.me/55DDDNUMERO', max_length=200, verbose_name='Link do WhatsApp (Botão Flutuante)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, help_text='Aparece no card do serviço na Home e na imagem do menu Soluções (dropdown).', null=True, upload_to='services/', verbose_name='Ícone/Imagem'),
        ),
    ]
