# Generated by Django 5.1.4 on 2026-08-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_navbarconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerconfig',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='footerconfig',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='cta_link',
            field=models.CharField(default='https://wa.me/5562995530750', max_length=200, verbose_name='Link do WhatsApp'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='cta_link',
            field=models.CharField(default='https://wa.me/5562995530750', max_length=200, verbose_name='Link do Botão'),
        ),
    ]
