# Generated by Django 5.1.4 on 2026-08-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_footerconfig_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='cta_link',
            field=models.CharField(default='#services', max_length=200, verbose_name='Link do Botão'),
        ),
    ]
