# Generated by Django 5.1.4 on 2026-08-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_herosection_cta_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto do Perfil'),
        ),
    ]
