# Generated by Django 5.1.4 on 2026-09-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_testimonial_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbarconfig',
            options={'verbose_name': 'Configurações Gerais (Logo e WhatsApp)', 'verbose_name_plural': 'Configurações Gerais (Logo e WhatsApp)'},
        ),
        migrations.RemoveField(
            model_name='navbarconfig',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='navbarconfig',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='navbarconfig',
            name='linkedin_link',
        ),
    ]
