# Generated by Django 5.1.4 on 2026-09-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_navbarconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifferentiatorsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Nossa cultura', max_length=50, verbose_name='Tag Superior (Laranja)')),
                ('title', models.CharField(default='Três pilares.\nSua operação mais eficiente.', help_text='Use uma quebra de linha para separar a primeira linha do título.', max_length=200, verbose_name='Título Principal')),
                ('subtitle', models.TextField(default='A Competec é o seu parceiro para aumentar a eficiência, previsibilidade e maturidade das operações industriais', verbose_name='Texto de Apoio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Seção Diferenciais (Capa)',
                'verbose_name_plural': 'Seção Diferenciais (Capa)',
            },
        ),
        migrations.CreateModel(
            name='PartnersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Cases', max_length=50, verbose_name='Tag Superior (Laranja)')),
                ('title', models.CharField(default='Transformando desafios\nem cases de sucesso.', help_text='Use uma quebra de linha para separar a primeira linha do título.', max_length=200, verbose_name='Título Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Seção Parceiros (Capa)',
                'verbose_name_plural': 'Seção Parceiros (Capa)',
            },
        ),
        migrations.AlterModelOptions(
            name='navbarconfig',
            options={'verbose_name': 'Configurações Gerais (Logo, WhatsApp e SEO)', 'verbose_name_plural': 'Configurações Gerais (Logo, WhatsApp e SEO)'},
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='differentiators_section_title',
            field=models.CharField(default='Nossos Diferenciais', max_length=200, verbose_name='Título da Seção Diferenciais'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='gallery_section_title',
            field=models.CharField(default='Nossa Estrutura', max_length=200, verbose_name='Título da Galeria'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='history_section_tag',
            field=models.CharField(default='Nossa Jornada', max_length=50, verbose_name='Tag da Seção História'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='history_section_title',
            field=models.CharField(default='História da Competec', max_length=200, verbose_name='Título da Seção História'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='partners_section_title',
            field=models.CharField(default='Empresas que confiam na Competec', max_length=200, verbose_name='Título da Seção Parceiros'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='Artigo', help_text='Selo exibido no card do post. Ex: Artigo, Notícia, Guia.', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='navbarconfig',
            name='seo_description',
            field=models.TextField(default='Especialistas em Automação, Metrologia e Manutenção Industrial.', help_text='Texto que aparece embaixo do link do site nos resultados do Google e quando o link é compartilhado.', max_length=200, verbose_name='Descrição para Buscadores (SEO)'),
        ),
        migrations.AddField(
            model_name='navbarconfig',
            name='seo_title',
            field=models.CharField(default='Competec - Soluções Industriais', help_text='Aparece na aba do navegador e no título dos resultados do Google, em todas as páginas do site.', max_length=70, verbose_name='Título da Aba do Navegador (SEO)'),
        ),
        migrations.AddField(
            model_name='testimonialssection',
            name='intro_text',
            field=models.CharField(default='Veja os depoimentos de quem confiou na Competec:', max_length=200, verbose_name='Texto acima do carrossel'),
        ),
    ]
