# Generated by Django 5.1.4 on 2026-09-08 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_seed_new_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='landing_authority_text',
            field=models.TextField(blank=True, verbose_name='Texto da seção de autoridade/confiança'),
        ),
        migrations.AddField(
            model_name='service',
            name='landing_authority_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título da seção de autoridade/confiança'),
        ),
        migrations.AddField(
            model_name='service',
            name='landing_benefits_text',
            field=models.TextField(blank=True, verbose_name='Texto da seção de benefícios'),
        ),
        migrations.AddField(
            model_name='service',
            name='landing_benefits_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título da seção de benefícios'),
        ),
        migrations.AddField(
            model_name='service',
            name='landing_callout',
            field=models.TextField(blank=True, verbose_name='Texto de destaque (caixa cinza abaixo das categorias)'),
        ),
        migrations.AddField(
            model_name='service',
            name='landing_equipment_text',
            field=models.TextField(blank=True, verbose_name='Texto da seção de equipamentos/soluções'),
        ),
        migrations.AddField(
            model_name='service',
            name='landing_equipment_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título da seção de equipamentos/soluções'),
        ),
        migrations.AddField(
            model_name='service',
            name='landing_final_cta',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título da faixa final (chamada de fechamento)'),
        ),
        migrations.AddField(
            model_name='service',
            name='landing_form_text',
            field=models.TextField(blank=True, verbose_name='Texto acima do formulário'),
        ),
        migrations.AddField(
            model_name='service',
            name='landing_form_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título acima do formulário'),
        ),
        migrations.AddField(
            model_name='service',
            name='use_landing_template',
            field=models.BooleanField(default=False, help_text='Ative para usar o layout de landing page com formulário de captura (usado hoje em Calibração e Usinagem). Deixe desativado para o layout padrão de serviço.', verbose_name='Usar layout de Landing Page?'),
        ),
        migrations.CreateModel(
            name='ServiceAuthorityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Aparece nos boxes de confiança logo abaixo do hero da landing page.', verbose_name='Texto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_points', to='core.service')),
            ],
            options={
                'verbose_name': 'Ponto de Autoridade (Landing Page)',
                'verbose_name_plural': 'Pontos de Autoridade (Landing Page)',
                'ordering': ['order'],
            },
        ),
    ]
